### PR TITLE
Add walls parameter for ROTT

### PR DESCRIPTION
**Pull request by Voros2**

### CODE REVIEW

**Comment by chungy** [comment]
I don't understand. What is this supposed to do?

**Comment by Voros2** [comment]
Apparently, Deutex has partial compatibility with ROTT, and supports extracting ROTT walls. In extract.c, there is a function for extracting walls (which are 64x64 bmp) from ROTT. But since there is no way to select walls via a -walls parameter, I'm not sure if it would be able to run that extraction.

Or maybe ROTT support should be removed?

**Comment by chungy** [comment]
This would have been great if you included it in the commit message so nobody has to guess. Can you edit your commit messages?

As for ROTT support, I've noticed and thought about it as well. No clue if it even works. If not, maybe better to remove. :)

**Comment by Voros2** [comment]
If it really does have ROTT support, then I guess it's a good thing to expand it. How many programs out there support ROTT anyway? Nowhere near as all the programs that support Doom.

**Comment by Voros2** [comment]
And I assumed "add walls parameter" would enough, since that's exactly what it does. And I don't have access to Git right now, so I can't :)

**Comment by NickZ** [comment]
Voros, have you tested ROTT support? Can you give us a low down on what actually happens when you try to extract/put together a ROTT data file?

**Comment by chungy** [comment]
We've decided to remove the existing ROTT instead. If you'd like to restore it and/or write new functionality to make it complete, we'll be happy to accept a future PR.

**Comment by NickZ** [comment]
We tested it out, and although we had some success extracting the files, it only extracts some of the pictures (some were messed up, it didn't extract the sounds, and we can't get it to compose a wad. We decided it was best to remove it, since we weren't willing to maintain stuff that would be little used, especially stuff that was only partially working.

**Pull request closed without merging**
