### PR TITLE
Change some default parameters

### PR DESCRIPTION
**Pull request by Voros2**
Because PPM and AU are ancient formats not used anymore.
Also make fullsnd true.

### CODE REVIEW

**Comment by chungy** [comment]
PNG will be a better default picture format. Let's hold until that's in (actively working with Nick now on it)

**Comment by Voros2** [comment]
There is a piece of specific code in extract.c that forces -xtract to save in BMP format, unless specified with -ppm, -png or -gif.  I assume that piece of code isn't necessary?

**Comment by chungy** [comment]
Can you point to where it is? I don't see it.

**Comment by Voros2** [comment]
It starts somewhere around line 40, with XTRbmpSave. Or maybe the comment above it is misleading?

**Comment by chungy** [comment]
I believe it's a misleading comment from before DeuTex supported other formats.

**Pull request merged**
