### PR TITLE
Add PNG Support

### PR DESCRIPTION
**Pull request by NickZ**
PNG Export and Import are now fully working. I have added a 3-BSD  library (http://lodev.org/lodepng/) to enable this functionality. 

It can import any type of PNG (PNG8+transparency, PNG24, PNG32), and will export to a PNG8+transparency.

I have tested this with Freedoom. I have been able to export the entire wad to PNG, and I was able to subsequently build freedoom with all the sprites and flats replaced with PNGs. Other than a build error when building the help screen (the script explicitly looks for the .gifs), it works perfectly.

### CODE REVIEW

**Comment by Voros2** [comment]
Yes!

**Comment by chungy** [comment]
I'm not entirely comfortable with importing an entire library into the tree, especially one so large. Can it be refactored to use an installed libpng instead?

**Comment by Voros2** [comment]
Should this be edited to include -png: 
https://github.com/Doom-Utils/deutex/blob/master/deutex.6
?

**Comment by chungy** [comment]
Closing as the libpng-based implementation was merged. Thanks!

**Pull request closed without merging**
